{% set version = "4.1-10" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-hergm
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/hergm_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/hergm/hergm_{{ version }}.tar.gz
  sha256: 30f18b18d2c5b6b325c447fd12e1689980f1c3e51d69abacbc398dac6b2d7913

build:
  number: 3
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-matrix
    - r-rcpp >=0.12.7
    - r-ergm
    - r-igraph
    - r-intergraph
    - r-latentnet
    - r-mcgibbsit
    - r-mlergm
    - r-network
    - r-sna
    - r-stringr
  run:
    - r-base
    - r-matrix
    - r-rcpp >=0.12.7
    - r-ergm
    - r-igraph
    - r-intergraph
    - r-latentnet
    - r-mcgibbsit
    - r-mlergm
    - r-network
    - r-sna
    - r-stringr

test:
  commands:
    - $R -e "library('hergm')"           # [not win]
    - "\"%R%\" -e \"library('hergm')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=hergm
  license: GPL-3.0-only
  summary: Hierarchical exponential-family random graph models with local dependence. See Schweinberger and Luna (2018) <doi:10.18637/jss.v085.i01>.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - izahn
